name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true   # Caches gems for faster builds

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run Cucumber tests
        run: bundle exec cucumber
